### ISSUE TITLE
Write up short description of available FL parcel data

### ISSUE THREAD

**Issue by annarusso** [annarusso/fld#2]
Highlight potentially interesting LHS variables

**Comment by annarusso** [comment]
Description of parcel data (and flood map data are in Data/Data Notes. Still to do: 

1. Figure out if we can get 2011 Parcel data
2. Figure out if we can get 2011 (or any historical) flood hazard layer

**Comment by ostriker** [comment]
This department of revenue page suggests that we can get 2011 parcel data! See: http://www.fdot.gov/statistics/multimodaldata/multimodal/Florida%20Department%20of%20Revenue%20(DOR)%20Tax%20Parcel%20Data.pdf
(It says they have tax data from 1976 but that it is not available in GIS/parcel format.)

**Comment by annarusso** [comment]
Hi, 

Thanks!! I realized that the Dropbox organization must need some work, because that PDF you link to was in the /data/ directory :) I reorganized and put stuff into a FLD-2 folder under /tasks/.

I was excited because there is supposedly 2011, but it isn't available (or I couldn't find it???) on the data portal linked to in Data Notes under [FLD-2]. So I think we / I still need to call Florida to see how we can get it. But still... it exists!

Anna

**Comment by ostriker** [comment]
Oops, I didn't see that! I also checked the data portal and didn't find anything.... BUT I have found this:
http://floridarevenue.com/property/Pages/DataPortal_RequestAssessmentRollGISData.aspx (click on "request prior data") It looks like we can request a lot of the prior data! I think we want the NAL files (these assess the value of the immovable property, whereas the NAP files assess movable items... I think) as well as the sales data, which could be really useful. 

I'm happy to take the initiative if you want to get this data request process started now. Let me know!

**Comment by annarusso** [comment]
Amazing find!! I think we want both the GIS and NAL files? Because we want the geolocation (in GIS) with information about the parcel (in NAL I think). I think we can do a merge on county-parcel-ID. But it may be worthwhile to see if we could get in touch with someone to make sure we are requesting the right thing before we submit a request? But I think that once we have an idea of what dataset we want, it definitely doesn't hurt to start the data request now. I'm happy to see if I can reach someone from Florida Dept of Rev? You know how much I love cold calling... :)

File type aside, It looks like they have GIS files from 2005-2017. I think we should definitely request 2011...maybe in the future we may want more pre-period but for now I think easiest to just stick with 2011? Wdyt? 

Anna

**Comment by ostriker** [comment]
Closing because we got all the data!!
