### ISSUE TITLE
Get technologically acquainted

### ISSUE THREAD

**Issue by annarusso** [annarusso/fld#3]
Learn Git
Learn ArcGIS

**Comment by annarusso** [comment]
Some links for Git:

https://docs.google.com/document/d/1hvs8_5x5sGdJtI0WQYqC79aLV83wTvHtBXVu7KVG6b8/edit
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by annarusso** [comment]
for downloading arcGIS: https://ist.mit.edu/arcgis/license

**Comment by ostriker** [comment]
Additional GIS resources from MIT libraries: https://libguides.mit.edu/gis/tutorials

**Comment by ostriker** [comment]
How to use ArcGIS at MIT:

Option 1: Use the GIS lab in Rotch Library. Quote from libraries help email: "It's a fairly large program so the computers in the GIS lab are best equipped to run it and you'll be able to get help with GIS over in Rotch." Help hours are Mon-Fri, 2-3pm, or email gishelp@mit.edu.

Option 2: Use the Econ computers in the graduate student lounge(s). This can be done once we've switched our accounts from the current setup (meant to be used on a local computer, aka "local") to the grad student version (meant to be used on all computers, aka "roaming"). Note that this may cause some issues with Dropbox, not sure exactly what though. This information comes from a conversation I just had with Carl. He also noted that ArcGIS is run on Windows only, but people with Macs can run it using VMware if they want.

**Comment by ostriker** [comment]
@annarusso I am currently learning Git from this interactive application and would recommend it so far: https://learngitbranching.js.org/ 

Also, I don't understand everything on this page but it explains some Git things in terms of SVN, which may be helpful: https://git-scm.com/course/svn.html

**Comment by ostriker** [comment]
It looks like MIT has an arrangement with GitHub that will allow us to create a private repository: http://kb.mit.edu/confluence/pages/viewpage.action?pageId=153816140 
We should think about setting this up!

**Comment by ostriker** [comment]
I found this intro to GIS exercise to be useful: https://libguides.mit.edu/ld.php?content_id=6600695
The data for the exercise is found here: https://libguides.mit.edu/c.php?g=176295&p=1161397#17032172
("Intro to GIS Data", under the "Introduction to GIS & Mapping" heading)

I did this on the Rotch GIS computers. They have GIS help hours from 2-3pm M-F.

**Comment by annarusso** [comment]
Awesome, thanks!! Will get myself there soon...
