### ISSUE TITLE
Set up a git repository

### ISSUE THREAD

**Issue by ostriker** [annarusso/fld#5]
Set up a git repository for the project on the MIT server

**Comment by ostriker** [comment]
Hi @annarusso,

I have set up a private repository on github.mit.edu. Here are instructions for the one-time setup:

- Make an account on github.mit.edu (this will let us use a private repository) (I've already set up a private repository for FLD.) ** Email me your username so I can add you as a collaborator. **
- Log in to the MIT Econ servers and generate an SSH key:
ssh-keygen -t rsa -b 4096 -C <email>
This will create files id_rsa and id_rsa.pub in ~/.ssh. 
- Add the ssh key to your keychain:
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
- Add the public key to your MIT Github account (github.mit.edu):
Copy the contents of id_rsa.pub
Go to Settings > SSH and GPG Keys > New SSH Key. In the title field you can write something descriptive, like "MIT Econ server". Paste the contents of the key into the second field. See: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

- Make a directory to hold your copy of the repository
- In that directory, clone the repository by typing: "git clone git@github.mit.edu:ostriker/fld.git" (I think you will only be able to do this after I add you as a collaborator)

To get new changes, run "git pull". To learn more about how to use git, see 
https://www.learnenough.com/git-tutorial/
(I don't know how much you know about git already... I only skimmed the stuff about branching, not sure how much we want to use that functionality but I think we can figure it out!)

Let me know if you run into issues that you can't figure out. I found the LearnEnough tutorial combined with the GitHub help pages to pretty much cover everything I needed, though, so I think it shouldn't be too bad!

**Comment by annarusso** [comment]
@ostriker 
question: should we migrate the issues from here to the private github repository you set up? That way things are in the same place? Is there any added functionality to that? If so, it seems incredibly low cost to do that now...

**Comment by ostriker** [comment]
I think that makes a lot of sense! Not sure that adds very much functionality but even so, it would be less silly :) If you agree, I'm happy to migrate the issues over (fancy word for copy & paste) today. Lmk!

**Comment by ostriker** [comment]
Done! All further discussion should happen on the other repository.
